spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false       # 콘솔에 SQL 출력
    properties:
      hibernate:
        format_sql: true  # SQL 예쁘게 출력
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: localhost
      port: 6379
#      password: redis_password  # Redis 비밀번호 설정 (필요 시)

  # 필요 시 timezone 설정
  jackson:
    time-zone: Asia/Seoul

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # 바인딩 파라미터 출력
